image: elixir:latest

cache:
  paths:
  - deps/

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test:
  stage: test
  script:
  - mix test --cover
  artifacts:
    paths:
    - cover

docs:
  stage: deploy
  script:
  - mix docs
  only:
  - master
  artifacts:
    paths:
    - doc
