image: elixir:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ingest_repo_test
  POSTGRES_USER: ingest
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test:
  stage: test
  script:
    - mix test --cover
  artifacts:
    paths:
      - cover

pages:
  stage: deploy
  script:
  - mix docs --output public
  artifacts:
    paths:
    - public
  only:
  - master
