image: elixir:latest

cache:
  paths:
  - deps/


variables:
  MIX_ENV: test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test:
  stage: test
  script:
  - mix test

docs:
  stage: deploy
  script:
  - mix docs
  - mv doc public
  only:
  - master
  artifacts:
    paths:
    - public
