apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingest
spec:
  selector:
    matchLabels:
      app: ingest
  serviceName: ingest-cluster
  replicas: 2
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
      - name: ingest
        image: coplusco/ingest:latest
        env:
          - name: RELEASE_DISTRIBUTION
            value: name
          - name: RELEASE_COOKIE
            value: "cookie"
        ports:
        - name: http
          protocol: TCP
          containerPort: 4000
